// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIFcvrsNmkI4QplnptjxY3xbbxCSX8GQ',
    appId: '1:750904261479:web:d50a5540929fb76b364dc2',
    messagingSenderId: '750904261479',
    projectId: 'ejar-8df74',
    authDomain: 'ejar-8df74.firebaseapp.com',
    storageBucket: 'ejar-8df74.firebasestorage.app',
    measurementId: 'G-ZQ9K1T9ZSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEWDlYtv4MZLyp1RqqsU_-EyGvZlBvto',
    appId: '1:750904261479:android:0a703bf9fad51b8b364dc2',
    messagingSenderId: '750904261479',
    projectId: 'ejar-8df74',
    storageBucket: 'ejar-8df74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5Pdh5towtjoBaBSRInLz3n4-yBJOCHg',
    appId: '1:750904261479:ios:94c66e3812725a41364dc2',
    messagingSenderId: '750904261479',
    projectId: 'ejar-8df74',
    storageBucket: 'ejar-8df74.firebasestorage.app',
    iosBundleId: 'com.example.ejar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5Pdh5towtjoBaBSRInLz3n4-yBJOCHg',
    appId: '1:750904261479:ios:94c66e3812725a41364dc2',
    messagingSenderId: '750904261479',
    projectId: 'ejar-8df74',
    storageBucket: 'ejar-8df74.firebasestorage.app',
    iosBundleId: 'com.example.ejar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDIFcvrsNmkI4QplnptjxY3xbbxCSX8GQ',
    appId: '1:750904261479:web:c77fadf217975aa5364dc2',
    messagingSenderId: '750904261479',
    projectId: 'ejar-8df74',
    authDomain: 'ejar-8df74.firebaseapp.com',
    storageBucket: 'ejar-8df74.firebasestorage.app',
    measurementId: 'G-F19KZEHPCC',
  );

}